find_package(MPI REQUIRED)
if(MPI_FOUND)
  message("MPI found")
  if(NOT MPI_CXX_INCLUDE_DIRS)
        # Set manually to CRAY_MPICH_DIR/include
        set(MPI_CXX_INCLUDE_DIRS "$ENV{CRAY_MPICH_DIR}/include")
        message(STATUS "Manually setting MPI include dirs to: ${MPI_CXX_INCLUDE_DIRS}")
        set(MPI_LIBRARIES "$ENV{CRAY_MPICH_DIR}/lib/libmpi.so")
        message(STATUS "Manually setting MPI lib dirs to: ${MPI_LIBRARIES}")
  endif()
  list(APPEND QSIM_EXT_LIBRARIES
    ${MPI_LIBRARIES})
  list(APPEND QSIM_INCLUDE_DIRS
    ${MPI_CXX_INCLUDE_DIRS})
  message( STATUS "MPI libraries : ${MPI_LIBRARIES}" )
  message( STATUS "MPI include dirs : ${MPI_CXX_INCLUDE_DIRS}" )
  message("QSIM_INCLUDE_DIRS mpi: ${QSIM_INCLUDE_DIRS}")
else()
  message( FATAL_ERROR "MPI not found")
endif()
